### ISSUE TITLE
iOS compatible?

### ISSUE THREAD

**Issue by alelordelo** [nobuyuki83/delfem2#1]
Great to see a FEM solver project! : )

Would the solver run on Xcode iOS project targeting iPad Pro?

**Comment by nobuyuki83** [comment]
Thanks for having interest in our project! 
I don't have much knowledge in iOS project. If the 

Currently I'm assuming the use in desktop application.

**Comment by alelordelo** [comment]
Thanks Noboyuki, only read your reply now (not sure why GitHub didn't send an email notification).

The thing is that iOS now deprecated OpenGL, so it would have to be ported to Metal I believe... Would it be complex to rewrite the OpenGL part to Metal?

How Delfem compares to Jan Bender PBD in terms of performance?

**Comment by nobuyuki83** [comment]
I have been working with this issue for two years. 

I completely separated the graphics part and simulation part. If someone wants to use DelFEM2 from iOS, he/she can use it without graphics. 

So far, I don't have any plan to part to Metal. That too much work, unfortunately.
