### ISSUE TITLE
bw compatibility

### ISSUE THREAD

**Issue by kjaft** [nobuyuki83/delfem2#83]
Hey,
just discovered this - great, thanks for the new version! Just one simple question - is the interface at least to some degree compatible with DelFEM (old version)? I am just dealing with a project that uses the old version.

thanks!

**Comment by nobuyuki83** [comment]
Thanks for the question! 

> is the interface at least to some degree compatible with DelFEM (old version)? 

Unfortunately, No. I've never given thought about the backward compatibility before. But many of the classes should have the similar interfaces.
