### ISSUE TITLE
Is it possible to use delfem2 for mesh rigid and non-rigid registration?

### ISSUE THREAD

**Issue by 1939938853** [nobuyuki83/delfem2#85]
Hello, 

delfem2 looks great. 

I just wonder if  it is possible to use delfem2 for rigid and non-rigid mesh registration? How?

Thank you in advance!

**Comment by nobuyuki83** [comment]
This example is for non-rigid mesh registration:
https://github.com/nobuyuki83/delfem2/tree/master/examples_glfwold/625_DefLaplacianFitProj

We don't have any rigid registration examples (e.g., ICP) yet.
