### ISSUE TITLE
A typo error in examples_oldgl_glfw_cnpy README

### ISSUE THREAD

**Issue by tomcatmew** [nobuyuki83/delfem2#89]
1. https://smpl.is.tue.mpg.de/downloads no longer available, the new SMPL download address is https://smpl.is.tue.mpg.de/download.php, and you have to register on their website for download
2. `pip3 install chmpy` should be `pip3 install chumpy`

**Comment by nobuyuki83** [comment]
Thanks for pointing it out. I fixed the issue.  https://github.com/nobuyuki83/delfem2/commit/70bb48059728c0636f5254b5c252ff23f98d9cc9
